### PR TITLE
Fix IGN service Provider and set it as default provider

### PR DESCRIPTION
**Pull request by lspg**
Hi, i installed altiProfile and had to fix some stuff to make the IGN Provider work with the new api url and free shared key.
(as mentioned in your readme).
I also took the liberty to set it as the default provider, as the key is now shared and free for use and it works out of the box.
Hope it helps, thanks a lot great work.

### CODE REVIEW

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
@mdouchin can you review this pull request ?

**Comment by mdouchin** [comment]
Thanks @lspg for your contribution. Could you please also change the default values listed in https://github.com/3liz/lizmap-altiProfil/blob/master/altiProfil/classes/altiProfil.listener.php#L8 ?

**Comment by rldhont** [comment]
thanks @lspg

**Comment by lspg** [comment]
my pleasure :) keep on the good work

**Pull request merged**
